name: "CI"
on:
  # push:
  #   branches:
  #     - "dev"
  #     - "test"
  #     - "master"
  pull_request:
    types: [closed]
    branches:
      - "dev"
      - "test"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Conventional-commit & Semantic-release
        run: |
          branch_name=${{ github.ref }}
          repo_name=${{ github.event.repository.name }}
          user_name=${{ github.actor }}
          user_email="${{ github.actor }}@coolbitx.com"
          trigger_release="true"
          token=${{ secrets.GITHUB_TOKEN }}

          curl --header "Authorization: token ${token}" \
          --header 'Accept: application/vnd.github.v3.raw' \
          --remote-name \
          --location https://api.github.com/repos/ookangzheng/my-raw-cmd/contents/main.sh

          chmod +x main.sh
          ./main.sh $repo_name $branch_name $user_name $user_email $trigger_release $token
