name: "CI"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello world
        uses: ./
        with:
          branch_name: "dev"
          repo_name: ${{ github.event.repository.name }}
          user_name: ${{ github.actor }}
          trigger_release: "true"
          token: ${{ secrets.GITHUB_TOKEN }}
