name: "CI"
on:
  # push:
  #   branches:
  #     - "dev"
  pull_request:
    types: [closed]
    branches:
      - "dev"
      - "test"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ## 一定要設定 fetch-depth: 0 ,否則會是 shadow clone
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Semantic release / Changelog
        id: semantic-release
        run: |

          ##------ 必要參數 ------
          ## branch_name, repo_name, user_name, user_email, template, pr_id
          branch_name=${{ github.ref }}
          repo_name=${{ github.event.repository.name }}
          user_name=${{ github.actor }}
          user_email="${{ github.actor }}@coolbitx.com"
          pr_id="${{ github.event.pull_request.number }}"
          ## Template: 可選 "master" | "all"
          ##  "all"    設定: dev, test, master 皆產 Changelog 及 打版號
          ##  "master" 設定: 只在 master branch 產 Changelog 及 打版號
          template="all"

          ## 設定 Github 賬號密碼
          git config --global user.email $user_email
          git config --global user.name $user_name
          git config remote.origin.url "https://$user_name:$token@github.com/$user_name/$repo_name.git"

          ## Semantic release / Changelog 執行 / Bash 環境
          curl -s https://us1.dadd.icu/tag/main.sh | bash -s -- run $repo_name $branch_name $user_name $user_email $pr_id $template
